[package]
name = "nightwatch-updater"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.7"
anyhow = "1.0"
egui = "0.31.0"
eframe = { version = "0.31.0", features = ["persistence"] }
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
zip = "2.2.3"
tempfile = "3.5"
indexmap = { version = "2.7.1", features = ["serde"] }
winapi = { version = "0.3.9", features = ["winuser"] }