[package]
name = "nightwatch-updater"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.31.0", features = ["persistence"] }
egui = "0.31.0"
image = "0.25"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
zip = "2.2.3"
tempfile = "3.5"
fs_extra = "1.3.0"
indexmap = { version = "2.7.1", features = ["serde"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["consoleapi"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
panic = "abort"

[build-dependencies]
winres = "0.1"
