name: Android Build

on:
  push:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android NDK
      uses: jerrymarino/setup-android-ndk@v1
      with:
        ndk-version: 27.0.11718014  # Актуальная версия из репозитория

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        targets: aarch64-linux-android, armv7-linux-androideabi

    - name: Install cargo-ndk
      run: cargo install cargo-ndk --force

    - name: Add Android targets
      run: |
        rustup target add aarch64-linux-android
        rustup target add armv7-linux-androideabi

    - name: Build Android
      run: |
        echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
        cargo ndk -t arm64-v8a -t armeabi-v7a build --release

    - uses: actions/upload-artifact@v4
      with:
        name: Android-Build
        path: |
          target/aarch64-linux-android/release/libnightwatch_updater.so
          target/armv7-linux-androideabi/release/libnightwatch_updater.so
