name: Android Build

on:
  push:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 1. Установка базовых инструментов
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip zip openjdk-17-jdk

    # 2. Установка Android NDK
    - name: Setup NDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip commandlinetools-linux-*.zip -d cmdline-tools
        yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$GITHUB_WORKSPACE "ndk;26.2.11394342"
        echo "NDK_HOME=$GITHUB_WORKSPACE/ndk/26.2.11394342" >> $GITHUB_ENV

    # 3. Установка Rust и cargo-ndk
    - name: Install Rust tools
      run: |
        # Добавляем cargo-ndk в глобальные инструменты
        cargo install cargo-ndk --force
        
        # Обязательно добавляем путь к cargo в PATH
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        
        # Проверяем установку
        cargo ndk --version

    # 4. Сборка проекта
    - name: Build
      run: |
        export PATH="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
        cargo ndk -t aarch64-linux-android build --release
