name: Android Build

on:
  push:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;26.1.10909125"
        echo "NDK_HOME=$ANDROID_HOME/ndk/26.1.10909125" >> $GITHUB_ENV
        echo "$ANDROID_HOME/ndk/26.1.10909125" >> $GITHUB_PATH

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        targets: aarch64-linux-android, armv7-linux-androideabi

    - name: Install cargo-ndk
      run: cargo install cargo-ndk --force

    - name: Build Android
      run: |
        cargo ndk -t aarch64-linux-android -t armv7-linux-androideabi build --release

    - uses: actions/upload-artifact@v4
      with:
        name: Android-Build
        path: |
          target/aarch64-linux-android/release/libnightwatch_updater.so
          target/armv7-linux-androideabi/release/libnightwatch_updater.so
