name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest  # Меняем здесь на Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ImageMagick (для генерации иконки)
        run: choco install imagemagick -y

      - name: Generate Windows Icon
        run: |
          convert.exe -background none `
            -define icon:auto-resize=256,64,32 `
            resources/emblem.png `
            resources/emblem.ico

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Release
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: |
            target/x86_64-pc-windows-msvc/release/nightwatch-updater.exe
            resources/emblem.ico
