name: Android Build

on:
  push:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Android NDK
      run: |
        sudo apt-get install -y android-ndk
        echo "NDK_HOME=/usr/lib/android-ndk" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=/usr/lib/android-ndk" >> $GITHUB_ENV

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        targets: aarch64-linux-android, armv7-linux-androideabi
        override: true

    - name: Verify Rust targets
      run: |
        rustup target list --installed
        rustc -vV

    - name: Install cargo-ndk
      run: |
        cargo install cargo-ndk --force
        echo "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

    - name: Build Android
      run: |
        cargo ndk -t aarch64-linux-android -t armv7-linux-androideabi build --release

    - uses: actions/upload-artifact@v4
      with:
        name: Android-Build
        path: |
          target/aarch64-linux-android/release/libnightwatch_updater.so
          target/armv7-linux-androideabi/release/libnightwatch_updater.so
