name: Android Build

on:
  push:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Android NDK
      uses: anderskristo/android-sdk-cmdline-tools@v4.0.1
      with:
        ndk-version: "26.2.11394342"

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        targets: aarch64-linux-android, armv7-linux-androideabi, x86_64-linux-android, i686-linux-android
        override: true

    - name: Verify targets
      run: rustup target list --installed

    - name: Install cargo-ndk
      run: cargo install cargo-ndk --force

    - name: Build Android
      run: |
        export PATH="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
        cargo ndk -t aarch64-linux-android build --release

    - uses: actions/upload-artifact@v4
      with:
        name: Android-Binaries
        path: |
          target/aarch64-linux-android/release/libnightwatch_updater.so
