name: Android Build

on:
  push:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 1. Установка базовых компонентов Rust
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rust-src
        targets: aarch64-linux-android

    # 2. Устранение конфликтов с предустановленными утилитами
    - name: Clean conflicting tools
      run: |
        rm -f ~/.cargo/bin/{rust-analyzer,rustfmt,cargo-fmt}

    # 3. Установка Android NDK
    - name: Install NDK
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip -qq commandlinetools-linux-*.zip -d cmdline-tools
        yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$GITHUB_WORKSPACE "ndk;26.2.11394342"
        echo "NDK_HOME=$GITHUB_WORKSPACE/ndk/26.2.11394342" >> $GITHUB_ENV

    # 4. Настройка окружения
    - name: Configure environment
      run: |
        echo "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
        echo "[target.aarch64-linux-android]" >> $GITHUB_WORKSPACE/.cargo/config.toml
        echo 'linker = "aarch64-linux-android33-clang"' >> $GITHUB_WORKSPACE/.cargo/config.toml

    # 5. Сборка проекта
    - name: Build
      run: cargo ndk -t aarch64-linux-android build --release
