name: Android Build

on:
  push:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    # Шаг 1: Загрузка кода из репозитория
    - uses: actions/checkout@v4

    # Шаг 2: Установка Java и базовых зависимостей
    - name: Install system tools
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip zip openjdk-17-jdk

    # Шаг 3: Скачивание Android SDK
    - name: Download Android Tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip commandlinetools-linux-*.zip -d cmdline-tools

    # Шаг 4: Установка NDK
    - name: Install Android NDK
      run: |
        cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$GITHUB_WORKSPACE "ndk;26.2.11394342"
        echo "NDK_HOME=$GITHUB_WORKSPACE/ndk/26.2.11394342" >> $GITHUB_ENV

    # Шаг 5: Настройка Rust
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        targets: aarch64-linux-android
        override: true

    # Шаг 6: Явная установка цели для Android
    - name: Add Android target
      run: rustup target add aarch64-linux-android

    # Шаг 7: Установка cargo-ndk
    - name: Install build tools
      run: |
        cargo install cargo-ndk --force
        echo "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

    # Шаг 8: Сборка проекта
    - name: Build
      run: cargo ndk -t aarch64-linux-android build --release

    # Шаг 9: Сохранение результата
    - uses: actions/upload-artifact@v4
      with:
        name: android-build
        path: target/aarch64-linux-android/release/libnightwatch_updater.so
