name: Android Build

on:
  push:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Установка JDK
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # Установка Android SDK и NDK
    - name: Setup Android
      uses: android-actions/setup-android@v2
      with:
        ndk-version: "26.1.10909125"
        cmake-version: "3.22.1"

    # Настройка Rust
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        targets: aarch64-linux-android, armv7-linux-androideabi

    # Установка cargo-ndk
    - name: Install cargo-ndk
      run: |
        cargo install cargo-ndk --force
        echo "$ANDROID_HOME/ndk/26.1.10909125" >> $GITHUB_PATH

    # Добавление Android targets
    - name: Add Android targets
      run: |
        rustup target add aarch64-linux-android
        rustup target add armv7-linux-androideabi

    # Сборка
    - name: Build Android
      run: |
        export ANDROID_NDK_HOME="$ANDROID_HOME/ndk/26.1.10909125"
        cargo ndk -t arm64-v8a -t armeabi-v7a build --release

    # Загрузка артефактов
    - uses: actions/upload-artifact@v4
      with:
        name: Android-Build
        path: |
          target/arm64-v8a/release/libnightwatch_updater.so
          target/armeabi-v7a/release/libnightwatch_updater.so
