name: Android Build

on:
  push:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Правильный способ установки Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: 26.1.10909125
    
    # Установка Rust
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        targets: aarch64-linux-android, armv7-linux-androideabi
    
    # Добавление Android targets
    - name: Add Android targets
      run: |
        rustup target add aarch64-linux-android
        rustup target add armv7-linux-androideabi
    
    # Сборка
    - name: Build Android
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH="$ANDROID_HOME/cmake/3.22.1/bin:$PATH"
        cargo ndk -t armeabi-v7a -t arm64-v8a build --release
    
    # Загрузка артефактов
    - uses: actions/upload-artifact@v4
      with:
        name: Android-Build
        path: |
          target/aarch64-linux-android/release/libnightwatch_updater.so
          target/armv7-linux-androideabi/release/libnightwatch_updater.so
