name: Android Build

on:
  push:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 1. Установка системных зависимостей
    - name: Install base tools
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip zip openjdk-17-jdk curl

    # 2. Установка Android NDK
    - name: Setup NDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip commandlinetools-linux-*.zip -d cmdline-tools
        yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$GITHUB_WORKSPACE "ndk;26.2.11394342"
        echo "NDK_HOME=$GITHUB_WORKSPACE/ndk/26.2.11394342" >> $GITHUB_ENV

    # 3. Настройка Rust
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        targets: aarch64-linux-android
        override: true

    # 4. Явная установка cargo-ndk
    - name: Install cargo-ndk
      run: |
        cargo install cargo-ndk --force
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH  # Ключевая строка!

    # 5. Проверка установки
    - name: Verify tools
      run: |
        cargo --version
        rustc --version
        cargo ndk --version  # Проверяем доступность команды

    # 6. Сборка проекта
    - name: Build Android
      run: |
        export PATH="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
        cargo ndk -t aarch64-linux-android build --release

    - uses: actions/upload-artifact@v4
      with:
        name: android-libs
        path: target/aarch64-linux-android/release/lib*.so
