name: Android Build

on:
  push:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 1. Установка Android NDK
    - name: Install NDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip commandlinetools-linux-*.zip -d cmdline-tools
        yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$GITHUB_WORKSPACE "ndk;26.2.11394342"
        echo "NDK_HOME=$GITHUB_WORKSPACE/ndk/26.2.11394342" >> $GITHUB_ENV

    # 2. Настройка Rust
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        targets: aarch64-linux-android
        override: true

    # 3. Установка cargo-ndk (без версии)
    - name: Install cargo-ndk
      run: |
        cargo install cargo-ndk --force
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    # 4. Проверка версии
    - name: Verify cargo-ndk
      run: cargo ndk --version

    # 5. Сборка
    - name: Build
      run: |
        export PATH="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
        cargo ndk -t aarch64-linux-android build --release
